# Generated by Django 4.0 on 2023-10-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopost',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='イメージ2'),
        ),
    ]
